######################################################################
# Automatically generated by qmake (2.01a) Fri May 1 11:47:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += /opt/qwt-5.2/src
INCLUDEPATH += /opt/qwt-5.2/src
LIBS        += -L/opt/qwt-5.2/lib -lqwt
ICON = model.icns

# Input
HEADERS += canvaspicker.h plot.h wizard.h
SOURCES += canvaspicker.cpp plot.cpp simple.cpp wizard.cpp
RESOURCES += basic-qwt.qrc
