######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 11 07:04:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += convertdialog.h
FORMS += convertdialog.ui
SOURCES += convertdialog.cpp main.cpp
