######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 10 15:35:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += /opt/qwt-5.1/src
INCLUDEPATH += /opt/qwt-5.1/src
LIBS        += -L/opt/qwt-5.1/lib -lqwt

# Input
HEADERS += canvaspicker.h plot.h wizard.h
SOURCES += canvaspicker.cpp plot.cpp simple.cpp wizard.cpp
RESOURCES += basic-qwt.qrc
